# Generated by Django 3.2 on 2022-12-13 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=64, verbose_name='Title')),
                ('link', models.URLField(blank=True, verbose_name='Link')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('service_type', models.CharField(choices=[('SIGNAL', 'Signal')], default='SIGNAL', max_length=16, verbose_name='Service type')),
                ('coin', models.CharField(choices=[('USDT', 'Usdt')], max_length=16, verbose_name='Coin')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Is visible')),
                ('subscription_fee', models.IntegerField(blank=True, null=True, verbose_name='Subscription fee')),
                ('subscription_coin', models.CharField(choices=[('USDT', 'Usdt')], max_length=16, verbose_name='Subscription coin')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media.media', verbose_name='Image')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service', related_query_name='services', to='user.profile', verbose_name='Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
