# Generated by Django 3.2 on 2022-12-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='coin',
            field=models.CharField(choices=[('USDT', 'usdt')], max_length=16, verbose_name='Coin'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('SIGNAL', 'signal')], default='SIGNAL', max_length=16, verbose_name='Service type'),
        ),
        migrations.AlterField(
            model_name='service',
            name='subscription_coin',
            field=models.CharField(choices=[('USDT', 'usdt')], max_length=16, verbose_name='Subscription coin'),
        ),
    ]
