# Generated by Django 3.2 on 2022-12-21 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_profile_state'),
        ('services', '0002_auto_20221213_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', related_query_name='services', to='user.profile', verbose_name='Profile'),
        ),
    ]
