# Generated by Django 3.2 on 2023-01-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20230108_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='state',
            field=models.CharField(choices=[('TRACKING', 'tracking'), ('REQUESTED', 'requested'), ('PENDING', 'pending'), ('PUBLISH', 'publish')], default='TRACKING', max_length=50, verbose_name='State'),
        ),
    ]
