# Generated by Django 3.2 on 2023-01-16 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_profile_default_name'),
        ('services', '0005_service_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='ROIHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_type', models.CharField(choices=[('WEEKLY', 'weekly'), ('MONTHLY', 'monthly')], max_length=16, verbose_name='History type')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_ready', models.BooleanField(default=False)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roi_history_services', related_query_name='roi_history_service', to='services.service', verbose_name='Service')),
            ],
        ),
        migrations.CreateModel(
            name='DailyROI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.FloatField(verbose_name='Percentage')),
                ('date', models.DateField(verbose_name='Date')),
                ('roi_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rois', related_query_name='roi', to='services.roihistory')),
            ],
        ),
        migrations.AddConstraint(
            model_name='roihistory',
            constraint=models.UniqueConstraint(fields=('service', 'history_type'), name='unique_history_type_per_service'),
        ),
        migrations.AddConstraint(
            model_name='dailyroi',
            constraint=models.UniqueConstraint(fields=('roi_history', 'date'), name='unique_roi_history_per_date'),
        ),
    ]
