# Generated by Django 3.2 on 2023-01-16 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_profile_default_name'),
        ('services', '0006_auto_20230116_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('payment_type', models.CharField(choices=[('FREE', 'Free'), ('TRIAL', 'Trial'), ('IRT_PAID', 'Irt Paid'), ('CRYPTO_PAID', 'Crypto Paid')], max_length=16, verbose_name='Payment type')),
                ('amount', models.FloatField(blank=True, null=True, verbose_name='Amount')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESSFUL', 'Successful'), ('FAILED', 'Failed')], default='PENDING', max_length=16, verbose_name='Status')),
                ('reference_id', models.CharField(blank=True, max_length=100, verbose_name='Reference id')),
                ('expire_time', models.DateTimeField(verbose_name='Expire time')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', related_query_name='subscription', to='services.service', verbose_name='Service')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', related_query_name='subscription', to='user.profile', verbose_name='Subscriber')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubscriptionInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('ipg_track_id', models.CharField(blank=True, help_text='Tracking code or reference id of theinternet payment gateway for this invoice', max_length=128, null=True, verbose_name='IPG track id')),
                ('usdt_amount', models.FloatField(verbose_name='USDT amount')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('reference_id', models.TextField(blank=True, max_length=128, null=True, verbose_name='Reference id')),
                ('additional_data', models.JSONField(default=dict, null=True, verbose_name='Additional data')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESSFUL', 'Successful'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired')], default='PENDING', max_length=16, verbose_name='Status')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Is paid')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_invoices', related_query_name='subscription_invoice', to='user.profile', verbose_name='Profile')),
                ('subscription', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment', related_query_name='payment', to='services.subscription', verbose_name='Subscription')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
