# Generated by Django 3.2 on 2023-01-16 20:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_subscription_subscriptioninvoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='reference_id',
        ),
        migrations.AddField(
            model_name='subscription',
            name='tracking_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Tracking code'),
        ),
    ]
