# Generated by Django 3.2 on 2023-01-16 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_auto_20230116_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='expire_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expire time'),
        ),
    ]
