# Generated by Django 3.2 on 2023-01-16 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_subscription_expire_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptioninvoice',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Is paid'),
        ),
    ]
