# Generated by Django 3.2 on 2023-01-20 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_remove_subscription_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptioninvoice',
            name='subscription',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice', related_query_name='invoice', to='services.subscription', verbose_name='Subscription'),
        ),
    ]
