# Generated by Django 3.2 on 2023-01-21 12:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_alter_subscriptioninvoice_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='platform_fee',
            field=models.IntegerField(blank=True, default=10, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Platform fee'),
        ),
    ]
