# Generated by Django 3.2 on 2023-01-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('services', '0014_alter_service_subscription_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='exchange',
            field=models.CharField(choices=[('COINEX', 'Coinex')], default='coinex', max_length=255, verbose_name='Exchange'),
            preserve_default=False,
        ),
    ]
