# Generated by Django 3.2 on 2023-01-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_service_exchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='watch_list',
            field=models.JSONField(blank=True, null=True, verbose_name='watch_list'),
        ),
    ]
