# Generated by Django 3.2 on 2023-01-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_service_watch_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roihistory',
            name='history_type',
            field=models.CharField(choices=[('WEEKLY', 'weekly'), ('MONTHLY', 'monthly'), ('THREE_MONTHLY', 'three_monthly')], max_length=16, verbose_name='History type'),
        ),
        migrations.AlterField(
            model_name='service',
            name='exchange',
            field=models.CharField(choices=[('COINEX', 'coinex')], max_length=255, verbose_name='Exchange'),
        ),
    ]
