# Generated by Django 3.2 on 2023-01-30 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_auto_20230130_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='watch_list',
            field=models.JSONField(default=list, verbose_name='watch_list'),
        ),
    ]
