# Generated by Django 3.2 on 2023-02-15 06:27

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_auto_20230208_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAggregatedPnl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.FloatField(verbose_name='Percentage')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('date', models.DateField(verbose_name='Date')),
            ],
        ),
        migrations.AlterModelManagers(
            name='subscription',
            managers=[
                ('factory', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='dailyroi',
            name='unique_roi_history_per_date',
        ),
        migrations.RemoveField(
            model_name='roihistory',
            name='is_ready',
        ),
        migrations.AddField(
            model_name='dailyroi',
            name='number',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='dailyroi',
            constraint=models.UniqueConstraint(fields=('roi_history', 'number'), name='unique_roi_history_per_number'),
        ),
        migrations.AddField(
            model_name='dailyaggregatedpnl',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_aggregated_pnls', related_query_name='daily_aggregated_pnl', to='services.service', verbose_name='Service'),
        ),
        migrations.AddConstraint(
            model_name='dailyaggregatedpnl',
            constraint=models.UniqueConstraint(fields=('date', 'service'), name='unique_aggregated_pnl_per_date_and_service'),
        ),
    ]
