# Generated by Django 3.2 on 2023-02-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_auto_20230208_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='exchanges',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Exchange'),
        ),
        migrations.AlterField(
            model_name='service',
            name='watch_list',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='watch_list'),
        ),
    ]
