# Generated by Django 3.2 on 2023-02-15 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_auto_20230215_0627'),
        ('services', '0020_auto_20230215_1034'),
    ]

    operations = [
    ]
