# Generated by Django 3.2 on 2023-02-19 11:32

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    Service = apps.get_model("services", "Service")
    db_alias = schema_editor.connection.alias
    services = Service.objects.using(db_alias)
    try:
        for service in services:
            if service.watch_list:
                service.watch_list = [s['coin'] for s in service.watch_list]
            if service.exchanges:
                service.exchanges = [e['exchange'] for e in service.exchanges]
            service.save()
    except Exception as e:
        print("Custom migration error", e)


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0021_merge_0020_auto_20230215_0627_0020_auto_20230215_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='exchanges',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Exchange'),
        ),
        migrations.AlterField(
            model_name='service',
            name='watch_list',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='watch_list'),
        ),
        migrations.RunPython(forwards_func, reverse_func)
    ]
