# Generated by Django 3.2 on 2023-02-22 14:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0022_auto_20230219_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='has_trial',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='platform_fee',
            field=models.IntegerField(blank=True, default=20, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Platform fee'),
        ),
    ]
