# Generated by Django 3.2 on 2023-02-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0023_auto_20230222_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptioninvoice',
            name='reference_id',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Reference id'),
        ),
    ]
