# Generated by Django 3.2 on 2023-02-27 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0024_alter_service_platform_fee'),
        ('services', '0024_alter_subscriptioninvoice_reference_id'),
    ]

    operations = [
    ]
