# Generated by Django 3.2 on 2023-03-01 14:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0026_auto_20230301_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='platform_fee',
            field=models.IntegerField(blank=True, default=20, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Platform fee'),
        ),
    ]
