# Generated by Django 3.2 on 2023-04-03 08:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0027_alter_service_platform_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='platform_fee',
            field=models.IntegerField(blank=True, default=10, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Platform fee'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('SIGNAL', 'signal'), ('COPY', 'copy')], default='SIGNAL', max_length=16, verbose_name='Service type'),
        ),
    ]
