# Generated by Django 3.2 on 2023-04-08 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0028_auto_20230403_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start time'),
        ),
    ]
