# Generated by Django 3.2 on 2023-05-10 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0030_alter_subscriptioninvoice_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
