# Generated by Django 3.2 on 2023-05-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0031_subscription_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Balance'),
        ),
    ]
