# Generated by Django 3.2 on 2023-06-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0032_service_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roihistory',
            name='history_type',
            field=models.CharField(choices=[('WEEKLY', 'weekly'), ('MONTHLY', 'monthly'), ('THREE_MONTHLY', 'three_monthly'), ('OVERALLY', 'overally')], max_length=16, verbose_name='History type'),
        ),
    ]
