# Generated by Django 3.2 on 2023-06-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0033_alter_roihistory_history_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='copy_exchange',
            field=models.CharField(blank=True, choices=[('bybit', 'bybit'), ('kucoin', 'kucoin')], max_length=16, verbose_name='Copy exchange'),
        ),
    ]
