# Generated by Django 3.2 on 2023-06-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0034_service_copy_exchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='copy_exchange',
            field=models.CharField(blank=True, choices=[('BYBIT', 'BYBIT'), ('KUCOIN', 'KUCOIN')], max_length=16, verbose_name='Copy exchange'),
        ),
    ]
