# Generated by Django 3.2 on 2023-07-01 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0035_alter_service_copy_exchange'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalService',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('services.service',),
        ),
    ]
