# Generated by Django 3.2 on 2023-06-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0035_alter_service_copy_exchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='draw_down',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='initial_draw_down',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
