# Generated by Django 3.2 on 2023-07-03 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0036_auto_20230627_1415'),
        ('services', '0036_signalservice'),
    ]

    operations = [
    ]
