# Generated by Django 3.2 on 2023-07-25 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0039_auto_20230722_1350'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coin',
        ),
    ]
