# Generated by Django 3.2 on 2023-07-29 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0040_delete_coin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-id'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['-expire_time'], 'verbose_name': 'Subscription', 'verbose_name_plural': 'Subscriptions'},
        ),
    ]
