# Generated by Django 3.2 on 2023-08-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0041_auto_20230729_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='copy_exchange',
            field=models.CharField(blank=True, choices=[('BYBIT', 'BYBIT'), ('KUCOIN', 'KUCOIN'), ('BINGX', 'BINGX')], max_length=16, verbose_name='Copy exchange'),
        ),
    ]
