# Generated by Django 3.2 on 2023-09-26 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0005_merge_20230923_0855'),
        ('services', '0043_create_support_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='discount_applied',
            field=models.BooleanField(default=False, verbose_name='Discount applied'),
        ),
        migrations.AddField(
            model_name='subscriptioninvoice',
            name='invitation_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscription_invoices', related_query_name='subscription_invoice', to='invitation.invitationcode', verbose_name='Invitation code'),
        ),
        migrations.AddField(
            model_name='subscriptioninvoice',
            name='previous_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Previous amount before discount'),
        ),
        migrations.AddField(
            model_name='subscriptioninvoice',
            name='previous_usdt_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Previous USDT amount before discount'),
        ),
    ]
