# Generated by Django 3.2 on 2023-09-30 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0006_invitebonus_inviter_referral_code'),
        ('services', '0044_auto_20230926_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptioninvoice',
            name='invitation_code',
        ),
        migrations.AddField(
            model_name='subscription',
            name='invitation_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscription_invoices', related_query_name='subscription_invoice', to='invitation.invitationcode', verbose_name='Invitation code'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='previous_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Previous amount before discount'),
        ),
    ]
