# Generated by Django 3.2 on 2023-10-01 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0042_alter_service_copy_exchange'),
        ('services', '0045_auto_20230930_1620'),
    ]

    operations = [
    ]
