# Generated by Django 4.2 on 2023-11-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0046_merge_20231001_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='is_visible',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Is visible'),
        ),
    ]
