# Generated by Django 4.2 on 2023-11-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0047_alter_service_is_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyaggregatedpnl',
            name='amount',
            field=models.FloatField(db_index=True, verbose_name='Amount'),
        ),
    ]
