# Generated by Django 4.2 on 2023-11-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0048_alter_dailyaggregatedpnl_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('SIGNAL', 'signal'), ('COPY', 'copy')], db_index=True, default='SIGNAL', max_length=16, verbose_name='Service type'),
        ),
    ]
