# Generated by Django 4.2 on 2023-11-06 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0047_alter_service_created_at_and_more"),
        ("services", "0049_alter_service_service_type"),
    ]

    operations = []
