# Generated by Django 4.2 on 2023-11-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0051_alter_service_created_at_alter_service_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyaggregatedpnl',
            name='date',
            field=models.DateField(db_index=True, verbose_name='Date'),
        ),
    ]
