# Generated by Django 4.2 on 2023-11-14 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0052_alter_dailyaggregatedpnl_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='history_used',
            field=models.BooleanField(default=False, verbose_name='History Used'),
        ),
    ]
