# Generated by Django 4.2 on 2023-12-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0053_service_history_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyaggregatedpnl',
            name='v_balance',
            field=models.FloatField(default=0.0, verbose_name='Virtual Balance'),
        ),
        migrations.AddField(
            model_name='dailyaggregatedpnl',
            name='v_balance_change',
            field=models.FloatField(default=0.0, verbose_name='Virtual Balance Change'),
        ),
    ]
