# Generated by Django 4.2 on 2024-01-01 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0055_fill_all_dailyaggregatedpnl_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyroi',
            name='amount',
            field=models.FloatField(default=0, verbose_name='Amount'),
        ),
    ]
