# Generated by Django 4.2 on 2024-01-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0056_dailyroi_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='payment_type',
            field=models.CharField(choices=[('FREE', 'Free'), ('TRIAL', 'Trial'), ('IRT_PAID', 'Irt Paid'), ('CRYPTO_PAID', 'Crypto Paid'), ('CRYPTO_GATEWAY_PAID', 'Crypto Gateway Paid'), ('CRYPTO_INTERNAL_PAID', 'Crypto Internal Paid')], max_length=64, verbose_name='Payment type'),
        ),
    ]
