# Generated by Django 3.2 on 2023-08-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='bucket',
            field=models.CharField(choices=[('image', 'image'), ('charts', 'charts')], default='image', max_length=64, verbose_name='Bucket'),
        ),
    ]
