# Generated by Django 3.2 on 2022-12-13 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IAMUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authentication_level', models.CharField(blank=True, max_length=64, null=True)),
                ('owner_id', models.PositiveIntegerField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email address')),
                ('is_active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('owner_id', models.PositiveIntegerField(unique=True, verbose_name='Owner id')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('username', models.CharField(max_length=100, verbose_name='Username')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_vendor', models.BooleanField(default=False, verbose_name='Is vendor')),
                ('state', models.CharField(choices=[('PUBLISH', 'Publish')], default='PUBLISH', max_length=16, verbose_name='State')),
                ('instagram_id', models.CharField(blank=True, max_length=24, verbose_name='Instagram id')),
                ('telegram_id', models.CharField(blank=True, max_length=24, verbose_name='Telegram id')),
                ('twitter_id', models.CharField(blank=True, max_length=24, verbose_name='Twitter id')),
                ('youtube_id', models.CharField(blank=True, max_length=24, verbose_name='Youtube id')),
                ('trading_view_id', models.CharField(blank=True, max_length=24, verbose_name='Trading view id')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media.media', verbose_name='Image')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorProfileAnalytic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analytics', models.JSONField(default=dict)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.profile', verbose_name='Profile')),
            ],
        ),
    ]
