# Generated by Django 3.2 on 2022-12-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(choices=[('PUBLISH', 'publish')], default='PUBLISH', max_length=16, verbose_name='State'),
        ),
    ]
