# Generated by Django 3.2 on 2023-01-09 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_profile_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofileanalytic',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.profile', verbose_name='Profile'),
        ),
    ]
