# Generated by Django 3.2 on 2023-01-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_vendorprofileanalytic_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='default_name',
            field=models.BooleanField(default=False),
        ),
    ]
