# Generated by Django 3.2 on 2023-01-21 12:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_edit_default_name_for_profile_id_15'),
    ]

    operations = [
        migrations.CreateModel(
            name='IAMAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=64)),
                ('actions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), default=list, size=None)),
                ('owner_id', models.PositiveBigIntegerField()),
            ],
            options={
                'managed': False,
            },
        ),
    ]
