# Generated by Django 3.2 on 2023-07-17 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_profile_created_at'),
        ('user', '0007_auto_20230712_1112'),
    ]

    operations = [
    ]
