# Generated by Django 3.2 on 2023-07-31 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_merge_20230717_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='follower_num',
            field=models.IntegerField(default=0, verbose_name='Follower num'),
        ),
        migrations.AddField(
            model_name='profile',
            name='following_num',
            field=models.IntegerField(default=0, verbose_name='Following num'),
        ),
        migrations.AddField(
            model_name='profile',
            name='subscriber_num',
            field=models.IntegerField(default=0, verbose_name='Subscriber num'),
        ),
        migrations.AddField(
            model_name='profile',
            name='subscription_num',
            field=models.IntegerField(default=0, verbose_name='Subscription num'),
        ),
    ]
