# Generated by Django 3.2 on 2023-09-10 15:23

from django.db import migrations
from django.db.models import Count

from signals.models import VendorFollower, UserFollowing
from user.models import Profile


class Migration(migrations.Migration):
    def forwards_func(apps, schema_editor):
        user_followers = VendorFollower.objects.values('vendor').annotate(follower_num=Count('follower')).order_by()
        user_following = UserFollowing.objects.values('user').annotate(following_num=Count('following')).order_by()
        user_followers_list = list()
        user_following_list = list()
        for item in user_followers:
            vendor_id = item['vendor']
            follower_num = item['follower_num']
            user_followers_list.append(Profile(id=vendor_id, follower_num=follower_num))
        for item in user_following:
            user_id = item['user']
            following_num = item['following_num']
            user_following_list.append(Profile(id=user_id, following_num=following_num))
        Profile.objects.bulk_update(user_followers_list, ['follower_num'])
        Profile.objects.bulk_update(user_following_list, ['following_num'])

    dependencies = [
        ('user', '0009_auto_20230731_1330'),
    ]

    operations = [
        migrations.RunPython(code=forwards_func, reverse_code=migrations.RunPython.noop)
    ]
