# Generated by Django 3.2 on 2023-09-17 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20230910_1523'),
        ('user', '0010_auto_20230917_1142'),
    ]

    operations = [
    ]
