# Generated by Django 3.2 on 2023-09-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_merge_0010_auto_20230910_1523_0010_auto_20230917_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='quick_signal',
            field=models.BooleanField(default=False, verbose_name='Quick Signal'),
        ),
    ]
