variables:
    FILE_NAME: social-deploy.yaml
    KUBE_PATH: python
    FILE_NAME_CELERY: social-celery.yaml
    KUBE_PATH_CELERY: celery
    PROJECT_NAME: social
    RUNNER_SONAR_LOGIN: sqp_ffbe022bd5cd2f4167c4001dc35383da8e9180ce
    RUNNER_SONAR_PROJECT_KEY: social
    IMAGE: ${PROJECT_NAME}:${CI_COMMIT_SHORT_SHA}
stages:
     - unit-tests
     - build
     - kubectl-apply
     - deploy-abriment
unit-tests:
    tags:
        - social-local-runner
    stage: build
    image:
        name: 14123110.100:4040/python-postgres:11
    script:
        - /bin/bash /usr/local/bin/docker-entrypoint.sh
        - pip install pip==23.2.1
        - pip install -r requirements.txt
        - cp config/.test.env src/core/.env
        - cd src && coverage run --source='.' manage.py test
        - coverage report
        - coverage xml
        - /sonar-scanner/sonar-scanner-4.7.0.2747-linux/bin/sonar-scanner -Dsonar.projectKey=${RUNNER_SONAR_PROJECT_KEY} -Dsonar.sources=. -Dsonar.host.url=http://162163629000 -D6onar.login=${RUNNER_SONAR_LOGIN} -Dsonar.python.version=3.11  -Dsonar.python.coverage.reportPaths=coverage.xml
    after_script:
        - 'curl -H "X-Auth-Token: ${X_AUTH_TOKEN}" -H "X-User-Id: ${X_USER_ID}"  -H "Content-type: application/json" -d "{\"message\": {  \"rid\": \"6499598da607d79a6c7439a7\", \"msg\": \" :clock10: ${CI_JOB_STARTED_AT} :clock10: [CI Job URL](${CI_JOB_URL})    announcement for the :test_tube: unit-test SOCIAL BACKEND :test_tube: ${CI_JOB_STATUS} on branch ${CI_COMMIT_REF_NAME} @all\" } }" https://chat.amnmoj.ir/api/v1/chat.sendMessage'
    only:
        refs:
            - /^dev\/.*$/
            - development
build-image:
    tags:
        - social-runner
    stage: build
    image:
        name: 15173210.100:4040/docker:20.10.16
    before_script:
        - echo ${NEXUS_PASS} | docker login --username gitlab-ci --password-stdin ${NEXUS_SERVER_PUSH}
    script:
        - docker build -t ${NEXUS_SERVER_PUSH}/${IMAGE}  -f Dockerfile .
        - docker push ${NEXUS_SERVER_PUSH}/${IMAGE}

    only:
        refs:
            - test
            - main
kubectl-apply:
    tags:
        -  social-image-runner
    stage: kubectl-apply
    script:
        - echo "Deploy project on online-server k8s"
        - bash /kubectl/k8s/script.sh  ${NEXUS_SERVER_PULL}/${IMAGE} ${FILE_NAME} ${KUBE_PATH}
        - bash /kubectl/k8s/script.sh  ${NEXUS_SERVER_PULL}/${IMAGE} ${FILE_NAME_CELERY} ${KUBE_PATH_CELERY}
    after_script:
        - 'curl -H "X-Auth-Token: ${X_AUTH_TOKEN}" -H "X-User-Id: ${X_USER_ID}"  -H "Content-type: application/json" -d "{\"message\": {  \"rid\": \"6499598da607d79a6c7439a7\", \"msg\": \" :clock10: ${CI_JOB_STARTED_AT} :clock10:  [CI Job URL](${CI_JOB_URL})   announcement for the :deploy: SOCIAL BACKEND :deploy: deploy on test.com == ${CI_JOB_STATUS} @all\" } }" https://chat.amnmoj.ir/api/v1/chat.sendMessage'
    only:
        refs:
            - test
deploy:
    stage: deploy-abriment
    tags:
        - social-abriment-shell
    script:
        - echo "Deploy project on abriment"
        - bash /kubectl/k8s/script.sh  docker.test.com/${IMAGE} ${FILE_NAME} ${KUBE_PATH}
        - bash /kubectl/k8s/script.sh  docker.test.com/${IMAGE} ${FILE_NAME_CELERY} ${KUBE_PATH_CELERY}    
    after_script:
        - 'curl -H "X-Auth-Token: ${X_AUTH_TOKEN}" -H "X-User-Id: ${X_USER_ID}"  -H "Content-type: application/json" -d "{\"message\": {  \"rid\": \"6499598da607d79a6c7439a7\", \"msg\": \" :clock10: ${CI_JOB_STARTED_AT} :clock10:  [CI Job URL](${CI_JOB_URL})  announcement for the :deploy: SOCIAL BACKEND :deploy: deploy on test.com == ${CI_JOB_STATUS} @all\" } }" https://chat.amnmoj.ir/api/v1/chat.sendMessage'
        - 'curl -H "X-Auth-Token: ${X_AUTH_TOKEN}" -H "X-User-Id: ${X_USER_ID}"  -H "Content-type: application/json" -d "{\"message\": {  \"rid\": \"gih9dkXMnsxcxpRby\", \"msg\": \" :clock10: ${CI_JOB_STARTED_AT} :clock10:  [CI Job URL](${CI_JOB_URL})  announcement for the :deploy: SOCIAL BACKEND :deploy: deploy on test.com == ${CI_JOB_STATUS} @all\" } }" https://chat.amnmoj.ir/api/v1/chat.sendMessage'

    only:
        refs:
            - main
