# Generated by Django 3.2 on 2022-12-13 10:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        ('user', '0001_initial'),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'exchange',
                'verbose_name_plural': 'exchanges',
            },
        ),
        migrations.CreateModel(
            name='ExchangeMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('exchange_name', models.CharField(max_length=32, verbose_name='Name')),
                ('coin_pair', models.CharField(max_length=32, verbose_name='Coin pair')),
                ('coin_name', models.CharField(max_length=32, verbose_name='Coin name')),
            ],
            options={
                'unique_together': {('exchange_name', 'coin_pair')},
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('primary_coin', models.CharField(max_length=50, verbose_name='Primary coin')),
                ('secoundary_coin', models.CharField(max_length=50, verbose_name='Secondary coin')),
            ],
            options={
                'verbose_name': 'market',
                'verbose_name_plural': 'markets',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='TradingSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('futures', 'futures'), ('spot', 'spot')], default='spot', max_length=255, verbose_name='Type')),
                ('position', models.CharField(blank=True, choices=[('long', 'long'), ('short', 'short')], default=None, max_length=255, null=True, verbose_name='Position')),
                ('leverage', models.PositiveBigIntegerField(default=1, verbose_name='Leverage')),
                ('percentage_of_found', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Percentage of found')),
                ('entry_point', models.PositiveBigIntegerField(default=0, verbose_name='Entry point')),
                ('entry_point_hit_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Entry point hit datetime')),
                ('take_profit_1', models.PositiveBigIntegerField(verbose_name='Take profit 1')),
                ('take_profit_1_hit_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Take profit 1 hit datetime')),
                ('take_profit_2', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Take_profit-2')),
                ('take_profit_2_hit_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Take profit 2 hit datetime')),
                ('volume', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Volume')),
                ('stop_los', models.PositiveBigIntegerField(verbose_name='Stop los')),
                ('stop_los_hit_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Stop loss hit datetime')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('state', models.CharField(choices=[('draft', 'draft'), ('test', 'test'), ('publish', 'publish'), ('start', 'start'), ('close', 'close'), ('deleted', 'deleted')], default='publish', max_length=256, verbose_name='State')),
                ('vip', models.BooleanField(default=False, verbose_name='Vip')),
                ('eid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_signals', to='signals.exchange', verbose_name='Exchange id')),
                ('exchange_market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_market_signals', to='signals.exchangemarket', verbose_name='Exchange market')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.media', verbose_name='Signal image')),
                ('market_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_signals', to='signals.market', verbose_name='Market id')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_signals', to='services.service', verbose_name='Service id')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', related_query_name='vendors', to='user.profile', verbose_name='Vendor')),
            ],
            options={
                'verbose_name': 'signals',
                'verbose_name_plural': 'trading-signals',
                'ordering': ('-id',),
            },
        ),
        migrations.AddField(
            model_name='exchange',
            name='market',
            field=models.ManyToManyField(related_name='exchanges', related_query_name='exchanges', to='signals.Market', verbose_name='Market'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, verbose_name='comment')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', related_query_name='authors', to='user.profile', verbose_name='Author')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', related_query_name='replies', to='signals.comment', verbose_name='Parent')),
                ('trading_signal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', related_query_name='comments', to='signals.tradingsignal', verbose_name='Trading signal')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
                'ordering': ('created_at',),
            },
        ),
    ]
