# Generated by Django 3.2 on 2022-12-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingsignal',
            name='position',
            field=models.CharField(blank=True, choices=[('LONG', 'long'), ('SHORT', 'short')], default=None, max_length=255, null=True, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='tradingsignal',
            name='state',
            field=models.CharField(choices=[('DRAFT', 'draft'), ('TEST', 'test'), ('PUBLISH', 'publish'), ('START', 'start'), ('CLOSE', 'close'), ('DELETED', 'deleted')], default='PUBLISH', max_length=256, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='tradingsignal',
            name='type',
            field=models.CharField(choices=[('FUTURES', 'futures'), ('SPOT', 'spot')], default='SPOT', max_length=255, verbose_name='Type'),
        ),
    ]
