# Generated by Django 3.2 on 2022-12-21 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_profile_state'),
        ('signals', '0002_auto_20221213_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradingsignal',
            name='eid',
        ),
        migrations.RemoveField(
            model_name='tradingsignal',
            name='market_id',
        ),
        migrations.AlterField(
            model_name='tradingsignal',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_signals', related_query_name='vendor_signals', to='user.profile', verbose_name='Vendor'),
        ),
        migrations.CreateModel(
            name='Vendorfollower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', related_query_name='followers', to='user.profile', verbose_name='Follower')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_followers', related_query_name='vendor_followers', to='user.profile', verbose_name='Vendor')),
            ],
            options={
                'verbose_name': 'followers',
                'verbose_name_plural': 'followers',
                'ordering': ('-id',),
                'unique_together': {('vendor', 'follower')},
            },
        ),
        migrations.CreateModel(
            name='Userfollowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Followings', related_query_name='Followings', to='user.profile', verbose_name='Following')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_Followings', related_query_name='User_Followings', to='user.profile', verbose_name='User Following')),
            ],
            options={
                'verbose_name': 'user-followings',
                'verbose_name_plural': 'user-followings',
                'ordering': ('-id',),
                'unique_together': {('user', 'following')},
            },
        ),
    ]
