# Generated by Django 3.2 on 2023-01-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0004_auto_20230101_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangemarket',
            name='exchange_name',
            field=models.CharField(max_length=32, verbose_name='Exchange name'),
        ),
    ]
