# Generated by Django 3.2 on 2023-01-09 11:46

from django.db import migrations, models



def set_pair_values(apps, schema_editor):
    ExchangeMarket = apps.get_model("signals", "ExchangeMarket")
    for ex_m in ExchangeMarket.objects.all():
        ex_m.base_currency = ex_m.coin_name.replace("USDT","").replace("/","")
        ex_m.save()

class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0005_alter_exchangemarket_exchange_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangemarket',
            name='base_currency',
            field=models.CharField(default='BTC', help_text='The base currency is always the first cryptocurrency in a crypto trading pair. The base currency is the base to which the other currency is compared – if we look at our EUR/USD example from earlier, euro (EUR) is the base currency. For BTC/USDT, BTC is the base currency. The ticker before the “/” is always the base currency in crypto. Another example is ETH/BTC, in which ETH is the base currency.', max_length=20, verbose_name='Base currency(AKA first pair)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exchangemarket',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='exchangemarket',
            name='market_type',
            field=models.CharField(choices=[('FUTURES', 'futures'), ('SPOT', 'spot')], default='FUTURES', max_length=10, verbose_name='Market type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exchangemarket',
            name='quote_currency',
            field=models.CharField(default='USDT', help_text='The second part is the quote currency.\nIt is the price of the base currency quoted using the quote currency.\nThe quote currency comes after the “/”. For the trading pair of BTC/USDT, USDT is the quote currency.\nIf we refer back to the EUR/USD example, the U.S. dollar (USD) is the quote currency.', max_length=20, verbose_name='Quote currency(AKA second pair)'),
            preserve_default=False,
        ),
        migrations.RunPython(set_pair_values, migrations.RunPython.noop)
    ]
