# Generated by Django 3.2 on 2023-01-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0006_auto_20230109_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangemarket',
            name='base_currency',
            field=models.CharField(help_text='The base currency is always the first cryptocurrency in a crypto trading pair.\n        The base currency is the base to which the other currency is compared – if we look at our EUR/USD \n        example from earlier, euro (EUR) is the base currency. For BTC/USDT, BTC is the base currency. \n        The ticker before the “/” is always the base currency in crypto. Another example is ETH/BTC, \n        in which ETH is the base currency.', max_length=20, verbose_name='Base currency(AKA first pair)'),
        ),
        migrations.AlterField(
            model_name='exchangemarket',
            name='coin_name',
            field=models.CharField(max_length=32, verbose_name='Coin display name'),
        ),
        migrations.AlterField(
            model_name='exchangemarket',
            name='quote_currency',
            field=models.CharField(help_text='The second part is the quote currency.\n        It is the price of the base currency quoted using the quote currency.\n        The quote currency comes after the “/”. For the trading pair of BTC/USDT, USDT is the quote currency.\n        If we refer back to the EUR/USD example, the U.S. dollar (USD) is the quote currency.', max_length=20, verbose_name='Quote currency(AKA second pair)'),
        ),
    ]
