# Generated by Django 3.2 on 2023-01-16 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0007_auto_20230111_1324'),
        ('signals', '0008_remove_tradingsignal_vendor'),
    ]

    operations = [
    ]
