# Generated by Django 3.2 on 2023-01-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0010_auto_20230116_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingsignal',
            name='manual_closure_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Manual closure price'),
        ),
    ]
