# Generated by Django 3.2 on 2023-01-21 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0011_tradingsignal_manual_closure_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exchangemarket',
            unique_together={('exchange_name', 'coin_pair', 'market_type')},
        ),
    ]
