# Generated by Django 3.2 on 2023-01-23 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_service_platform_fee'),
        ('signals', '0012_alter_exchangemarket_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingsignal',
            name='sid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_signals', related_query_name='service_signal', to='services.service', verbose_name='Service id'),
        ),
    ]
