# Generated by Django 3.2 on 2023-02-22 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0014_alter_tradingsignal_entry_point'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tradingsignal',
            options={'ordering': ('-created_at',), 'verbose_name': 'signals', 'verbose_name_plural': 'trading-signals'},
        ),
    ]
