# Generated by Django 3.2 on 2023-03-06 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_iamadmin'),
        ('signals', '0015_alter_tradingsignal_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfollowing',
            name='following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followings', related_query_name='following', to='user.profile', verbose_name='Following'),
        ),
        migrations.AlterField(
            model_name='userfollowing',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_followings', related_query_name='user_following', to='user.profile', verbose_name='User Following'),
        ),
        migrations.AlterField(
            model_name='vendorfollower',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', related_query_name='follower', to='user.profile', verbose_name='Follower'),
        ),
        migrations.AlterField(
            model_name='vendorfollower',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_followers', related_query_name='vendor_follower', to='user.profile', verbose_name='Vendor'),
        ),
    ]
