# Generated by Django 3.2 on 2023-04-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0016_auto_20230306_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangemarket',
            name='futures_symbol',
            field=models.CharField(blank=True, max_length=32, verbose_name='Futures symbol'),
        ),
    ]
