# Generated by Django 3.2 on 2023-05-03 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0018_alter_tradingsignal_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingsignal',
            name='position',
            field=models.CharField(blank=True, choices=[('LONG', 'long'), ('SHORT', 'short')], default=None, max_length=255, null=True, verbose_name='Position'),
        ),
    ]
