# Generated by Django 3.2 on 2023-06-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0019_alter_tradingsignal_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingsignal',
            name='child_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Child Id'),
        ),
        migrations.AddField(
            model_name='tradingsignal',
            name='edited_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Edited datetime'),
        ),
        migrations.AddField(
            model_name='tradingsignal',
            name='is_edited',
            field=models.BooleanField(default=False, verbose_name='Is Edited'),
        ),
        migrations.AddField(
            model_name='tradingsignal',
            name='parent_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Parent Id'),
        ),
    ]
