# Generated by Django 3.2 on 2023-06-25 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0020_auto_20230621_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingsignal',
            name='child_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_signal', related_query_name='child_signals', to='signals.tradingsignal', verbose_name='Child Id'),
        ),
        migrations.AlterField(
            model_name='tradingsignal',
            name='parent_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parent_signal', related_query_name='parent_signals', to='signals.tradingsignal', verbose_name='Parent Id'),
        ),
    ]
