# Generated by Django 3.2 on 2023-06-25 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0022_auto_20230625_0810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradingsignal',
            name='is_edited',
        ),
        migrations.RemoveField(
            model_name='tradingsignal',
            name='parent',
        ),
        migrations.AlterField(
            model_name='tradingsignal',
            name='child',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parent', related_query_name='parents', to='signals.tradingsignal', verbose_name='Child Id'),
        ),
    ]
