# Generated by Django 3.2 on 2023-07-31 12:56

from django.db import migrations, models

from signals.models import CoinDecimalNumber


class Migration(migrations.Migration):
    dependencies = [
        ('signals', '0024_auto_20230712_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinDecimalNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_pair', models.CharField(max_length=256, unique=True, verbose_name='Coin name')),
                ('decimal_num',
                 models.IntegerField(help_text='Number of decimal for each coin pair', verbose_name='Decimal Num')),
            ],
            options={
                'verbose_name': 'Coin Decimal Number',
                'verbose_name_plural': 'Coin Decimal Number',
                'ordering': ['coin_pair'],
            },
        ),
    ]
