# Generated by Django 3.2 on 2023-09-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('signals', '0027_change_value_coin_decimal_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingsignal',
            name='max_pnl_percentage',
            field=models.FloatField(blank=True, null=True, verbose_name='Max Pnl amount'),
        ),
        migrations.AddField(
            model_name='tradingsignal',
            name='min_pnl_percentage',
            field=models.FloatField(blank=True, null=True, verbose_name='Min Pnl amount'),
        ),
    ]
