# Generated by Django 3.2 on 2023-10-02 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_alter_media_bucket'),
        ('signals', '0029_fill_min_max_pnl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingsignal',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='media.media', verbose_name='Signal image'),
        ),
    ]
