# Generated by Django 4.2 on 2023-11-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0030_alter_tradingsignal_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingsignal',
            name='state',
            field=models.CharField(choices=[('DRAFT', 'draft'), ('TEST', 'test'), ('PUBLISH', 'publish'), ('START', 'start'), ('CLOSE', 'close'), ('DELETED', 'deleted')], db_index=True, default='PUBLISH', max_length=256, verbose_name='State'),
        ),
    ]
