# Generated by Django 4.2 on 2023-11-06 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("signals", "0031_alter_comment_created_at_alter_exchange_created_at_and_more"),
        ("signals", "0032_alter_tradingsignal_pnl_percentage"),
    ]

    operations = []
