# Generated by Django 4.2 on 2023-11-24 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0035_exchangemarket_tick_size'),
        ('signals', '0035_tradingsignal_virtual_value_signalvirtualbalance'),
    ]

    operations = [
    ]
