# Generated by Django 4.2 on 2023-11-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0036_merge_20231124_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingsignal',
            name='leverage',
            field=models.FloatField(default=1, verbose_name='Leverage'),
        ),
    ]
