# Generated by Django 4.2 on 2023-11-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0037_alter_tradingsignal_leverage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingsignal',
            name='virtual_value',
            field=models.FloatField(default=100, verbose_name='Virtual Value'),
        ),
    ]
