# Generated by Django 4.2 on 2023-12-09 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0039_alter_signalvirtualbalance_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingsignal',
            name='virtual_value',
            field=models.FloatField(default=10, verbose_name='Virtual Value'),
        ),
    ]
