# Generated by Django 4.2 on 2023-12-10 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0040_alter_tradingsignal_virtual_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingsignal',
            name='virtual_value',
            field=models.FloatField(default=0, verbose_name='Virtual Value'),
        ),
    ]
