# Generated by Django 4.2 on 2024-01-06 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0045_virtual_balance_into_1000'),
        ('signals', '0046_virtual_value_based_on_pof'),
    ]

    operations = [
    ]
