# Generated by Django 3.2 on 2023-09-17 08:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('assignor_type', models.CharField(choices=[('admin_level', 'admin_level'), ('user_level', 'user_level'), ('service_level', 'service_level')], max_length=128, verbose_name='Assignor type')),
                ('invitation_type', models.CharField(choices=[('percentage_discount', 'percentage_discount'), ('fixed_discount', 'fixed_discount'), ('fixed_addition', 'fixed_addition')], max_length=128, verbose_name='Invitation type')),
                ('invitation_amount', models.PositiveIntegerField(verbose_name='Invitation amount')),
                ('code_string', models.SlugField(max_length=512, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('only_assignor', models.BooleanField(verbose_name='Only assignor')),
                ('user_limit', models.PositiveIntegerField(verbose_name='User limit')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Start date')),
                ('expire_date', models.DateTimeField(blank=True, null=True, verbose_name='Expire date')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
