# Generated by Django 3.2 on 2023-09-19 08:49

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0002_invitebonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationcode',
            name='owner_id',
            field=models.PositiveBigIntegerField(default=0, verbose_name='owner id'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AssigneeEntities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('assignee_id', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None, verbose_name='Assignees id')),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignee_entities', to='invitation.invitationcode', verbose_name='Invitation code')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
