# Generated by Django 3.2 on 2023-09-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0002_invitebonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitebonus',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
