# Generated by Django 3.2 on 2023-09-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0003_invitebonus_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitebonus',
            name='amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
