# Generated by Django 3.2 on 2023-09-23 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0003_auto_20230919_0849'),
        ('invitation', '0004_alter_invitebonus_amount'),
    ]

    operations = [
    ]
