# Generated by Django 3.2 on 2023-09-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0005_merge_20230923_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitebonus',
            name='inviter_referral_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
