# Generated by Django 3.2 on 2023-10-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0006_invitebonus_inviter_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationcode',
            name='used_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Used count'),
        ),
    ]
