# Generated by Django 4.2 on 2023-11-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invitation", "0009_invitationreferral"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assigneeentities",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="invitationcode",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="invitationcodeusage",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="invitationreferral",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="invitebonus",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
