# Generated by Django 3.2 on 2023-03-01 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0006_iamadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopyTradingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('coin_pair', models.CharField(max_length=32, verbose_name='Coin pair')),
                ('order_type', models.CharField(max_length=32, verbose_name='Order type')),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4, verbose_name='Side')),
                ('amount', models.DecimalField(decimal_places=18, max_digits=30, verbose_name='Amount')),
                ('price', models.BigIntegerField(verbose_name='Price')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_orders', related_query_name='child_order', to='copytrading.copytradingorder', verbose_name='Parent Order')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', related_query_name='order', to='user.profile', verbose_name='Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
