# Generated by Django 3.2 on 2023-03-13 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_iamadmin'),
        ('copytrading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Name')),
                ('exchange', models.CharField(choices=[('COINEX', 'Coinex'), ('BYBIT', 'Bybit'), ('KUCOIN', 'Kucoin')], max_length=50, verbose_name='Exchange')),
                ('api_key', models.CharField(max_length=256, verbose_name='API Key')),
                ('secret_key', models.CharField(max_length=256, verbose_name='Secret Key')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copy_profile', related_query_name='copy_profiles', to='user.profile', verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'api-key',
                'verbose_name_plural': 'api-key',
                'ordering': ('-id',),
                'unique_together': {('exchange', 'api_key', 'secret_key')},
            },
        ),
    ]
