# Generated by Django 3.2 on 2023-04-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copytrading', '0003_auto_20230403_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='password',
            field=models.CharField(blank=True, max_length=30, verbose_name='Password'),
        ),
        migrations.AddField(
            model_name='tradingorder',
            name='symbol',
            field=models.CharField(blank=True, max_length=32, verbose_name='Symbol'),
        ),
    ]
