# Generated by Django 3.2 on 2023-04-29 08:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_iamadmin'),
        ('copytrading', '0004_auto_20230416_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='copysetting',
            name='stop_los',
        ),
        migrations.RemoveField(
            model_name='copysetting',
            name='take_profit',
        ),
        migrations.RemoveField(
            model_name='tradingorder',
            name='stop_los',
        ),
        migrations.AddField(
            model_name='copysetting',
            name='stop_loss_percentage',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Stop loss percentage'),
        ),
        migrations.AddField(
            model_name='copysetting',
            name='take_profit_percentage',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Take profit percentage'),
        ),
        migrations.AddField(
            model_name='tradingorder',
            name='exchange_order_id',
            field=models.CharField(blank=True, max_length=63),
        ),
        migrations.AddField(
            model_name='tradingorder',
            name='parent_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradingorder',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', related_query_name='order', to='user.profile', verbose_name='Profile'),
        ),
        migrations.AddField(
            model_name='tradingorder',
            name='stop_loss',
            field=models.FloatField(blank=True, null=True, verbose_name='Stop loss'),
        ),
        migrations.AddField(
            model_name='tradingorder',
            name='user_margin',
            field=models.FloatField(blank=True, null=True, verbose_name='User margin'),
        ),
        migrations.AddField(
            model_name='tradingorder',
            name='user_stop_loss_percentage',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='User stop los percentage'),
        ),
        migrations.AddField(
            model_name='tradingorder',
            name='user_take_profit_percentage',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Uesr take profit percentage'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', related_query_name='api_key', to='user.profile', verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='tradingorder',
            name='entry_point',
            field=models.FloatField(blank=True, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='tradingorder',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='tradingorder',
            name='state',
            field=models.CharField(choices=[('OPEN', 'Open'), ('OPEN_POSITION', 'Open Position'), ('CLOSED_POSITION', 'Closed Position'), ('CANCELED', 'Canceled')], default='OPEN', max_length=16, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='tradingorder',
            name='take_profit',
            field=models.FloatField(blank=True, null=True, verbose_name='Take profit'),
        ),
        migrations.DeleteModel(
            name='CopyTradingOrder',
        ),
    ]
