# Generated by Django 3.2 on 2023-05-03 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('copytrading', '0005_auto_20230429_0805'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('position', models.CharField(blank=True, choices=[('LONG', 'long_t'), ('SHORT', 'short')], max_length=8, verbose_name='Position')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('CANCELED', 'Canceled')], default='OPEN', max_length=20, verbose_name='Status')),
                ('realised_pnl', models.DecimalField(decimal_places=4, max_digits=4, verbose_name='Realised Pnl')),
                ('unrealised_pnl', models.DecimalField(decimal_places=4, max_digits=4, verbose_name='Realised Pnl')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='tradingorder',
            name='state',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CANCELED', 'Canceled')], default='OPEN', max_length=16, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='tradingorder',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trading_orders', related_query_name='trading_order', to='copytrading.position', verbose_name='Position'),
        ),
    ]
