# Generated by Django 3.2 on 2023-05-03 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copytrading', '0007_auto_20230503_0817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradingorder',
            name='order_id',
        ),
    ]
