# Generated by Django 3.2 on 2023-05-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copytrading', '0008_remove_tradingorder_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingorder',
            name='exit_point',
            field=models.FloatField(blank=True, null=True, verbose_name='Exit point'),
        ),
        migrations.AddField(
            model_name='tradingorder',
            name='filled_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Filled amount'),
        ),
        migrations.AddField(
            model_name='tradingorder',
            name='order_id',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Order_Id'),
        ),
        migrations.AddField(
            model_name='tradingorder',
            name='stop_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Stop price'),
        ),
        migrations.AlterField(
            model_name='position',
            name='realised_pnl',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=4, verbose_name='Realised Pnl'),
        ),
        migrations.AlterField(
            model_name='position',
            name='unrealised_pnl',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=4, verbose_name='Unrealised Pnl'),
        ),
        migrations.AlterField(
            model_name='tradingorder',
            name='state',
            field=models.CharField(choices=[('OPEN', 'Open'), ('PARTIALLY_FILLED', 'Partially Filled'), ('FILLED', 'Filled'), ('CANCELED', 'Canceled')], default='OPEN', max_length=16, verbose_name='State'),
        ),
    ]
