# Generated by Django 3.2 on 2023-05-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copytrading', '0009_auto_20230506_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='copysetting',
            name='filled',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=4, null=True, verbose_name='Filled'),
        ),
    ]
