# Generated by Django 3.2 on 2023-05-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copytrading', '0010_copysetting_filled'),
    ]

    operations = [
        migrations.AddField(
            model_name='copysetting',
            name='closed_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Closed Time'),
        ),
    ]
