# Generated by Django 3.2 on 2023-05-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copytrading', '0011_copysetting_closed_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='copysetting',
            name='closed_time',
        ),
        migrations.RemoveField(
            model_name='copysetting',
            name='filled',
        ),
        migrations.AddField(
            model_name='tradingorder',
            name='closed_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Closed Time'),
        ),
        migrations.AlterField(
            model_name='tradingorder',
            name='filled_amount',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=4, null=True, verbose_name='Filled amount'),
        ),
    ]
