# Generated by Django 3.2 on 2023-05-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copytrading', '0012_auto_20230507_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingorder',
            name='state',
            field=models.CharField(choices=[('NEW', 'New'), ('PARTIALLY_FILLED', 'Partially Filled'), ('FILLED', 'Filled'), ('CANCELED', 'Canceled')], default='NEW', max_length=16, verbose_name='State'),
        ),
    ]
