# Generated by Django 3.2 on 2023-05-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copytrading', '0013_alter_tradingorder_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradingorder',
            name='exit_point',
        ),
        migrations.AddField(
            model_name='position',
            name='exit_point',
            field=models.FloatField(blank=True, null=True, verbose_name='Exit point'),
        ),
    ]
