# Generated by Django 3.2 on 2023-05-08 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0030_alter_subscriptioninvoice_subscription'),
        ('copytrading', '0014_auto_20230508_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='exit_point',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, verbose_name='Exit point'),
        ),
        migrations.AlterField(
            model_name='tradingorder',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', related_query_name='order', to='copytrading.tradingorder', verbose_name='Parent Id'),
        ),
        migrations.AlterField(
            model_name='tradingorder',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_orders', related_query_name='service_order', to='services.service', verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='tradingorder',
            name='state',
            field=models.CharField(choices=[('New', 'New'), ('Active', 'Active'), ('PartiallyFilled', 'Partially Filled'), ('PartiallyFilledCanceled', 'Partially Filled Canceled'), ('Filled', 'Filled'), ('Cancelled', 'Cancelled'), ('Triggered', 'Triggered')], default='New', max_length=40, verbose_name='State'),
        ),
    ]
