# Generated by Django 3.2 on 2023-05-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copytrading', '0015_auto_20230508_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingorder',
            name='reduce_only',
            field=models.BooleanField(default=False),
        ),
    ]
