# Generated by Django 3.2 on 2023-05-10 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('copytrading', '0016_tradingorder_reduce_only'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradingorder',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='tradingorder',
            name='parent_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='copy_orders', related_query_name='copy_order', to='copytrading.tradingorder', verbose_name='Parent order'),
        ),
    ]
