# Generated by Django 3.2 on 2023-05-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copytrading', '0021_auto_20230516_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='side',
            field=models.CharField(blank=True, choices=[('LONG', 'long'), ('SHORT', 'short')], max_length=10, null=True, verbose_name='Side'),
        ),
    ]
