# Generated by Django 3.2 on 2023-05-21 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copytrading', '0023_rename_closed_datetime_position_closed_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='closed_at',
            new_name='closed_datetime',
        ),
    ]
