# Generated by Django 3.2 on 2023-05-21 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copytrading', '0020_auto_20230515_1233'),
        ('copytrading', '0024_rename_closed_at_position_closed_datetime'),
    ]

    operations = [
    ]
