# Generated by Django 3.2 on 2023-05-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copytrading', '0026_alter_position_avg_exit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='closed_pnl_percentage',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Closed pnl percentage'),
        ),
    ]
