# Generated by Django 3.2 on 2023-05-23 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copytrading', '0027_copysetting_is_active'),
        ('copytrading', '0027_position_closed_pnl_percentage'),
    ]

    operations = [
    ]
