# Generated by Django 3.2 on 2023-05-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copytrading', '0028_merge_20230523_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='entry_point',
            field=models.FloatField(blank=True, null=True, verbose_name='Entry point'),
        ),
        migrations.AddField(
            model_name='position',
            name='stop_loss',
            field=models.FloatField(blank=True, null=True, verbose_name='Stop loss'),
        ),
        migrations.AddField(
            model_name='position',
            name='take_profit',
            field=models.FloatField(blank=True, null=True, verbose_name='Take profit'),
        ),
        migrations.AlterField(
            model_name='tradingorder',
            name='entry_point',
            field=models.FloatField(blank=True, null=True, verbose_name='Entry point'),
        ),
    ]
