# Generated by Django 3.2 on 2023-05-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copytrading', '0030_rename_entry_point_position_entry_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='liquidation_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Liquidation Price'),
        ),
    ]
