# Generated by Django 3.2 on 2023-05-27 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copytrading', '0031_position_liquidation_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='entry_price',
        ),
    ]
