# Generated by Django 3.2 on 2023-05-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copytrading', '0032_remove_position_entry_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='closed_pnl_percentage',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=7, verbose_name='Closed pnl percentage'),
        ),
    ]
