# Generated by Django 3.2 on 2023-05-28 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0031_subscription_amount'),
        ('copytrading', '0034_position_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='position_services', related_query_name='position_service', to='services.service', verbose_name='Service'),
        ),
    ]
