# Generated by Django 3.2 on 2023-06-07 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0033_alter_roihistory_history_type'),
        ('user', '0006_iamadmin'),
        ('copytrading', '0035_position_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileServiceApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_service_api_keys', related_query_name='profile_service_api_key', to='copytrading.apikey', verbose_name='API Key')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_service_api_keys', related_query_name='profile_service_api_key', to='user.profile', verbose_name='Profile')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_service_api_keys', related_query_name='profile_service_api_key', to='services.service', verbose_name='Service')),
            ],
        ),
    ]
