# Generated by Django 3.2 on 2023-06-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copytrading', '0036_profileserviceapikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingorder',
            name='submission_error',
            field=models.TextField(null=True),
        ),
        migrations.AddConstraint(
            model_name='copysetting',
            constraint=models.UniqueConstraint(fields=('profile', 'service'), name='unique_setting_per_service_and_profile'),
        ),
    ]
