# Generated by Django 3.2 on 2023-06-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copytrading', '0037_auto_20230624_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingorder',
            name='state',
            field=models.CharField(choices=[('New', 'New'), ('Active', 'Active'), ('PartiallyFilled', 'Partially Filled'), ('PartiallyFilledCanceled', 'Partially Filled Canceled'), ('Filled', 'Filled'), ('Cancelled', 'Cancelled'), ('Triggered', 'Triggered'), ('open', 'Open'), ('closed', 'Closed'), ('failed', 'Failed')], default='open', max_length=40, verbose_name='State'),
        ),
    ]
