# Generated by Django 3.2 on 2023-08-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copytrading', '0039_auto_20230722_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingorder',
            name='filled_amount',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=14, null=True, verbose_name='Filled amount'),
        ),
    ]
