# Generated by Django 3.2 on 2023-08-09 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copytrading', '0040_alter_tradingorder_filled_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['-created_at'], 'verbose_name': 'Position', 'verbose_name_plural': 'Positions'},
        ),
        migrations.AlterField(
            model_name='tradingorder',
            name='state',
            field=models.CharField(choices=[('New', 'New'), ('Active', 'Active'), ('PartiallyFilled', 'Partially Filled'), ('PartiallyFilledCanceled', 'Partially Filled Canceled'), ('Filled', 'Filled'), ('Cancelled', 'Cancelled'), ('Triggered', 'Triggered'), ('open', 'Open'), ('closed', 'Closed'), ('failed', 'Failed'), ('x_open', 'X Open'), ('OpposeSideMarketClose', 'Oppose Side Market Close')], default='open', max_length=40, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='tradingorder',
            name='submission_error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
