# Generated by Django 3.2 on 2023-08-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copytrading', '0041_auto_20230809_0731'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tradingorder',
            options={'ordering': ['-created_at'], 'verbose_name': 'Trading Order', 'verbose_name_plural': 'Trading Order'},
        ),
        migrations.AlterField(
            model_name='apikey',
            name='exchange',
            field=models.CharField(choices=[('COINEX', 'Coinex'), ('BYBIT', 'Bybit'), ('KUCOIN', 'Kucoin'), ('BINGX', 'Bingx')], max_length=50, verbose_name='Exchange'),
        ),
    ]
