# Generated by Django 3.2 on 2023-09-20 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0029_fill_min_max_pnl'),
        ('copytrading', '0042_alter_tradingorder_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingorder',
            name='signal_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signal_refs', related_query_name='signal_ref', to='signals.tradingsignal', verbose_name='signal reference'),
        ),
    ]
