# Generated by Django 3.2 on 2023-09-25 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0029_fill_min_max_pnl'),
        ('copytrading', '0043_tradingorder_signal_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingorder',
            name='signal_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signal_orders', related_query_name='signal_order', to='signals.tradingsignal', verbose_name='signal reference'),
        ),
    ]
