# Generated by Django 3.2 on 2023-10-01 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copytrading', '0042_auto_20230820_1320'),
        ('copytrading', '0044_alter_tradingorder_signal_ref'),
    ]

    operations = [
    ]
