# Generated by Django 3.2 on 2023-10-11 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copytrading', '0045_tradingorder_api_key'),
        ('copytrading', '0046_auto_20231006_1859'),
    ]

    operations = [
    ]
