# Generated by Django 3.2 on 2023-10-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copytrading', '0047_merge_20231011_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingorder',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Amount'),
        ),
    ]
