# Generated by Django 3.2 on 2023-10-11 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copytrading', '0047_merge_20231011_1146'),
        ('copytrading', '0047_merge_20231011_1545'),
    ]

    operations = [
    ]
