# Generated by Django 3.2 on 2023-10-20 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copytrading', '0048_alter_tradingorder_amount'),
        ('copytrading', '0048_merge_20231011_1553'),
    ]

    operations = [
    ]
