# Generated by Django 4.2 on 2023-11-01 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("copytrading", "0050_auto_20231029_1414"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="avg_entry_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=14,
                null=True,
                verbose_name="Avg Entry Price",
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="avg_exit_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=14,
                null=True,
                verbose_name="Avg Exit point",
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="unrealised_pnl",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=14,
                null=True,
                verbose_name="Unrealised Pnl",
            ),
        ),
    ]
