# Generated by Django 4.2 on 2023-11-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("copytrading", "0051_alter_position_avg_entry_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apikey",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="position",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="tradingorder",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
