# Generated by Django 4.2 on 2023-11-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "copytrading",
            "0052_alter_apikey_created_at_alter_position_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=14,
                null=True,
                verbose_name="Quantity",
            ),
        ),
        migrations.AddField(
            model_name="position",
            name="value",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=14,
                null=True,
                verbose_name="Value",
            ),
        ),
        migrations.AlterField(
            model_name="tradingorder",
            name="state",
            field=models.CharField(
                choices=[
                    ("New", "New"),
                    ("Active", "Active"),
                    ("PartiallyFilled", "Partially Filled"),
                    ("PartiallyFilledCanceled", "Partially Filled Canceled"),
                    ("FILLED", "Filled"),
                    ("Cancelled", "Cancelled"),
                    ("Triggered", "Triggered"),
                    ("open", "Open"),
                    ("closed", "Closed"),
                    ("failed", "Failed"),
                    ("x_open", "X Open"),
                    ("X_CLOSED", "X Closed"),
                    ("OpposeSideMarketClose", "Oppose Side Market Close"),
                ],
                default="open",
                max_length=40,
                verbose_name="State",
            ),
        ),
    ]
