# Generated by Django 4.2 on 2023-11-13 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "copytrading",
            "0053_alter_apikey_created_at_alter_apikey_is_deleted_and_more",
        ),
        ("copytrading", "0053_position_quantity_position_value_and_more"),
    ]

    operations = []
