# Generated by Django 4.2 on 2023-11-13 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copytrading', '0053_alter_apikey_created_at_alter_apikey_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='exchange_name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Exchange'),
        ),
    ]
