# Generated by Django 4.2 on 2023-11-14 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("copytrading", "0054_merge_20231113_1636"),
        ("copytrading", "0054_position_exchange_name"),
    ]

    operations = []
