# Generated by Django 4.2 on 2023-11-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copytrading', '0055_merge_20231114_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='leverage',
            field=models.FloatField(blank=True, null=True, verbose_name='Leverage'),
        ),
    ]
