# Generated by Django 4.2 on 2023-11-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copytrading', '0056_alter_position_leverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Is Default'),
        ),
    ]
