# Generated by Django 4.2 on 2023-12-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copytrading', '0057_apikey_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingorder',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Quantity'),
        ),
    ]
