# Generated by Django 4.2 on 2023-12-09 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copytrading', '0057_apikey_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingorder',
            name='leverage',
            field=models.FloatField(blank=True, null=True, verbose_name='Leverage'),
        ),
    ]
