# Generated by Django 4.2 on 2023-12-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copytrading', '0058_tradingorder_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingorder',
            name='filled_amount',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=14, null=True, verbose_name='Filled amount'),
        ),
    ]
