# Generated by Django 4.2 on 2023-12-10 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copytrading', '0058_alter_tradingorder_leverage'),
        ('copytrading', '0059_alter_tradingorder_filled_amount'),
    ]

    operations = [
    ]
