# Generated by Django 4.2 on 2023-12-11 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copytrading', '0060_merge_20231210_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copysetting',
            name='margin',
            field=models.FloatField(default=2.0, verbose_name='Margin'),
        ),
    ]
