# Generated by Django 4.2 on 2023-12-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copytrading', '0061_alter_copysetting_margin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='exchange',
            field=models.CharField(choices=[('COINEX', 'Coinex'), ('BYBIT', 'Bybit'), ('KUCOIN', 'Kucoin'), ('BINGX', 'Bingx'), ('NOBITEX', 'Nobitex')], max_length=50, verbose_name='Exchange'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='secret_key',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Secret Key'),
        ),
    ]
