# Generated by Django 4.2 on 2023-12-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copytrading', '0062_alter_apikey_exchange_alter_apikey_secret_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingorder',
            name='avg_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True, verbose_name='Average Price'),
        ),
    ]
