# Generated by Django 4.2 on 2023-12-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copytrading', '0063_tradingorder_avg_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='exchange_position_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Exchange PositionId'),
        ),
    ]
