# Generated by Django 4.2 on 2023-12-19 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copytrading', '0064_position_exchange_position_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='liquidation_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Liquidation Price'),
        ),
    ]
