# Generated by Django 4.2 on 2023-12-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copytrading', '0065_alter_position_liquidation_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='avg_entry_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='Avg Entry Price'),
        ),
        migrations.AlterField(
            model_name='position',
            name='avg_exit_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='Avg Exit point'),
        ),
    ]
