# Generated by Django 4.2 on 2023-12-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copytrading', '0066_alter_position_avg_entry_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='closed_pnl',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=15, verbose_name='Closed Pnl'),
        ),
    ]
