# Generated by Django 3.2 on 2023-08-27 14:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('campaign_key', models.SlugField(max_length=512, unique=True, verbose_name='Campaign key')),
                ('campaign_name', models.TextField(verbose_name='Campaign name')),
                ('campaign_name_fa', models.TextField(verbose_name='Campaign name FA')),
                ('campaign_description', models.TextField(verbose_name='Campaign description')),
                ('campaign_description_fa', models.TextField(verbose_name='Campaign description FA')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start time')),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='End time')),
                ('show', models.BooleanField(verbose_name='Show')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
